---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
dependencies:
  # renovate: datasource=conda depName=conda-forge/coreutils
  - conda-forge::coreutils=9.5
  # renovate: datasource=conda depName=conda-forge/gawk
  - conda-forge::gawk=5.3.0