---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-updhmm=1.4.0
  - r-optparse=1.7.3