---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-genomicranges=1.54.1
  - r-dplyr=1.1.4
  - r-optparse=1.7.3